packages:
  - server
  - web
saveExact: true
overrides:
  "miniflare@4.20260730.0>undici": "7.29.1"
  "@esbuild-kit/core-utils@3.3.2>esbuild": "0.28.2"
allowBuilds:
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
